// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:any):Promise<main.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetTasks():Promise<Array<main.Task>>;

export function ToggleTaskCompletion(arg1:string):Promise<void>;
